// APP ACTIONS
export const APP_ACTION = 'APP_ACTION';

export const GET_RESOURCES_REQUESTED = 'GET_RESOURCES_REQUESTED';
export const GET_RESOURCES_SUCCEEDED = 'GET_RESOURCES_SUCCEEDED';
export const GET_RESOURCES_FAILED = 'GET_RESOURCES_FAILED';

export const RESOURCES_GET_EVENTS_REQUESTED = 'RESOURCES_GET_EVENTS_REQUESTED';
export const RESOURCES_GET_EVENTS_SUCCEEDED = 'RESOURCES_GET_EVENTS_SUCCEEDED';
export const RESOURCES_GET_EVENTS_FAILED = 'RESOURCES_GET_EVENTS_FAILED';

export const SHOW_RESOURCES = 'SHOW_RESOURCES';
export const SELECT_RESOURCE = 'SELECT_RESOURCE';
export const STORE_EVENTS = 'STORE_EVENTS';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';

export const CREATE_MEETING_REQUESTED = 'CREATE_MEETING_REQUESTED';
export const CREATE_MEETING_SUCCEEDED = 'CREATE_MEETING_SUCCEEDED';
export const CREATE_MEETING_FAILED = 'CREATE_MEETING_FAILED';

export const RESTORE_AFTER_CRASH = 'RESTORE_AFTER_CRASH';
export const TOUCH_EVENT = 'TOUCH_EVENT';


export const CANCEL_MEETING_REQUESTED = 'CANCEL_MEETING_REQUESTED';
export const CANCEL_MEETING_SUCCEEDED = 'CANCEL_MEETING_SUCCEEDED';
export const CANCEL_MEETING_FAILED = 'CANCEL_MEETING_FAILED';

export const CONFIRM_MEETING_REQUESTED = 'CONFIRM_MEETING_REQUESTED';
export const CONFIRM_MEETING_SUCCEEDED = 'CONFIRM_MEETING_SUCCEEDED';
export const CONFIRM_MEETING_FAILED = 'CONFIRM_MEETING_FAILED';

export const BASE_MODAL_OPEN = 'BASE_MODAL_OPEN';
export const CANCEL_MODAL_OPEN = 'CANCEL_MODAL_OPEN';
export const MODAL_SYNC = 'MODAL_SYNC';

export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD';
export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION';
export const SET_CONFIGURATION = 'SET_CONFIGURATION';

export const CANCEL_SWIPE_TIMER = 'CANCEL_SWIPE_TIMER';
export const START_SWIPE_TIMER = 'START_SWIPE_TIMER';
export const SWIPE_BACK = 'SWIPE_BACK';
export const SWIPE_SYNC = 'SWIPE_SYNC';
